apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-detector-notifier
spec:
  selector:
    matchLabels:
      app: car-detector-notifier
  template:
    metadata:
      labels:
        app: car-detector-notifier
    spec:
      containers:
        - name: car-detector-notifier
          image: akos0628/car-detector-notifier:{{ .Values.env.APP_VERSION }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
