apiVersion: v1
kind: Service
metadata:
  name: car-detector-notifier
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: car-detector-notifier